In [41]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [42]:
# In a Jupyter notebook, often:
import sys
sys.path.append('/home/stefan/Projects/toxic-reasoning/')

In [43]:
import json
import itertools
import os
import warnings

import numpy as np
import pandas as pd

from sklearn.metrics import cohen_kappa_score
from statsmodels.stats.inter_rater import fleiss_kappa, aggregate_raters

from data import _preprocess, COLUMNS

### LOAD TEST SET

In [44]:
# TEST_DATA_FILE_NAME = '../data/temporal/preprocessed_test.pkl'
# TEST_DATA_FILE_NAME = '../data/temporal/preprocessed+manual_test.pkl'
TEST_DATA_FILE_NAME = '../data/temporal/preprocessed+manual+corrected_test.pkl'

test_df = _preprocess(pd.read_pickle(TEST_DATA_FILE_NAME))

# TODO fix this upstream somewhere
# test_df['answer_pp_toxicity'] = test_df['answer_toxicity']

# extract language from filename
test_df['lang'] = test_df['filename'].str.extract(r'batch_(..)_\d+\.csv')
test_df['lang'].unique()

array(['ar', 'de', 'en', 'es', 'nl', 'tr'], dtype=object)


### LOAD GPT ANNOTATIONS

In [45]:
TEST_PRED_FOLDER = '../data/temporal/gpt4o_2025-01-22_12-03-30'

gpt_df = pd.concat([pd.read_csv(os.path.join(TEST_PRED_FOLDER, f)) for f in os.listdir(TEST_PRED_FOLDER) if f.endswith('.csv')])

# expand answer field
df_answers = gpt_df['answer'].apply(json.loads).apply(json.loads).apply(pd.Series).add_prefix('answer_')
df_answers = df_answers.where(df_answers.astype(bool), np.nan)  # removes empty dictionaries and replaces with NaN
gpt_df = pd.concat([gpt_df.drop(columns='answer'), df_answers], axis=1)

# split up trinary
gpt_df['answer_toxicity'] = gpt_df['answer_trinary'].apply(lambda a: 'Yes/Maybe' if a['_Yes/Maybe'] else 'No')
gpt_df['answer_counternarrative'] = gpt_df['answer_trinary'].apply(lambda a: 'Yes' if a['_Counter-speech'] else 'No')

# further preprocessing
gpt_df = _preprocess(gpt_df)
gpt_df['workerid'] = 'gpt4o'
# pred_df['answer_implTopic'] = pred_df['answer_implTopic'].str.extract(r'^(?:\.\.\.\s)?(\(..?.?\))')

In [46]:
# Langauge misidentifications (See https://docs.google.com/spreadsheets/d/1K7AHawqNgLOV4SryJGr_BbQFwcB8K4gPOR9Xattx5Q4)
MISIDENTIFIED_THREAD_IDS = {
    '60761694404071785', '5687396952074376', '48407333198278932', '53501753679094372',
    '54288785178874084', '66024864922700717', '71880017305366941', '16353993833502616',
    '43223883605944201', '50032915589739384', '52097527239380956',
}
gpt_df = gpt_df[~gpt_df['st_id'].isin(MISIDENTIFIED_THREAD_IDS)]

### COMBINE

In [47]:
df = pd.concat([test_df, gpt_df])
df.shape

(11630, 144)

# Pre-processing

Add field for 'did someone fill out an implication'

In [48]:
# impl1 = df['answer_pp_englishImplication'].str.len() > 0
# impl2 = df['answer_pp_implication'].str.len() > 0
# impl3 = df['answer_pp_nativeImplication'].str.len() > 0
# df['nonEmptyImplication'] = impl1 | impl2 | impl3
#
#
df['answer_pp_hasOther'] = df['answer_pp_hasOther'].apply(str)


df = df.drop(df.index[
    df['workerid'].isin(['piek', 'isa']) & (df['lang'] == 'en')
])

# Export for manual inspection

In [49]:
df.to_csv('agreement_data.csv')

In [50]:
df.shape

(11507, 144)

In [51]:
# df.pivot(
#     columns=['workerid'], index=['comment_id'], values=['answer_implication']
# ).to_csv('implications.csv')
# df.pivot(
#     columns=['workerid'], index=['st_id', 'st_nr', 'comment_body'], values=['answer_toxicity']
# ).to_csv('first_question_a.csv')
# df.pivot(
#     columns=['workerid'], index=['st_id', 'st_nr', 'comment_body'], values=['answer_counternarrative']
# ).to_csv('first_question_b.csv')
# df.pivot(
#     columns=['workerid'], index=['comment_id'], values=['answer_justInappropriate']
# ).to_csv('second_question.csv')
# df.pivot(
#     columns=['workerid', 'comment_body'], index=['comment_id'], values=['answer_implication']
# ).to_csv('implications_with_comments.csv')

# ...

In [52]:
def conditional_calculation(df, all_calcs, do_calc, **kwargs):
    """
    Iterates over a list of calculation configurations, filters the dataframe according to specified conditions,
    and applies a calculation function to each relevant subset for specified columns.

    Parameters:
        df (pd.DataFrame): The dataframe to calculate on
        all_calcs (list): List of dictionaries, each defining a calculation with conditions, columns, prefixes, and labels.
        do_calc (callable): Function to run for each subset, expects arguments (suitable_df, column, prefix, labels)
    """
    for calc in all_calcs:
        # Start with all comment IDs as suitable candidates
        suitable_comment_ids = set(df['comment_id'].tolist())
        # Apply all conditions defined for this calculation
        for args in calc['conditions']:
            condition, *args = args
            if condition == 'full_agreement':
                # Find comment_ids where all annotators have identical (non-NaN) answers for the specified column
                column = args
                agreed = df.groupby(by=['comment_id'])['answer_pp_' + column].nunique() == 1
                comment_ids = set(agreed.index[agreed])
            elif condition == 'full_agreement_on_value':
                # Find comment_ids where all annotators set the target value (possibly after a mapping) for the given column
                column, value = args
                def mapping(x):
                    if column not in COLUMNS:   # the COLUMNS dict defines how text-values should map onto identifiers
                        return x
                    return COLUMNS[column].apply_fn(x)
                
                # This line creates a boolean Series that is True for comments where all annotators have the same value for the specified column.
                # It uses the mapping function to transform the column values before comparison.
                correct = df.groupby(by=['comment_id'])['answer_pp_' + column].apply(
                    lambda grp: (grp.map(mapping) == value).all()
                )
                comment_ids = set(correct.index[correct])
            elif condition == 'column_in_list':
                # Find comment_ids where the column value is included in the provided set/list of values
                column, values = args
                comment_ids = set(df[df[column].isin(values)]['comment_id'].tolist())
            else:
                # Any unrecognized condition raises an error
                raise ValueError()
            # Narrow down the suitable_comment_ids to those matching this condition
            suitable_comment_ids = suitable_comment_ids & comment_ids

        # Subset the dataframe to only include rows matching all conditions, sorted by comment_id
        suitable_df = df[df['comment_id'].isin(suitable_comment_ids)].sort_values('comment_id')

        # For every target column in 'to_calculate', run the calculation, passing the filtered df, column key, prefix, and provided labels
        for col in calc['to_calculate']:
            do_calc(suitable_df, col, calc['prefix'], calc['labels'], **kwargs)

# Calculate Agreements

In [53]:
# df.groupby(['lang', 'workerid'])[['st_id', 'st_nr']].apply(lambda grp: grp.value_counts().shape).reset_index()
df.groupby(['lang', 'workerid'])[['answer_pp_implDetected']].apply(lambda grp: grp.sum()).reset_index()

   lang         workerid  answer_pp_implDetected
0    ar    husseinsarrar                     113
1    ar            ilham                      99
2    ar             nada                      70
3    de  alexandra_genis                      94
4    de       jennystock                      48
5    de          mfrosin                     111
6    en            baran                     194
7    en             ilia                     143
8    en           stefan                     108
9    es           angela                      89
10   es           emmako                     163
11   es           felipe                     240
12   nl              isa                     121
13   nl             piek                      99
14   nl           stefan                      79
15   tr              alp                      78
16   tr            doruk                      43
17   tr           selman                      75

In [54]:
df.groupby('filename')['workerid'].apply(lambda grp: grp.value_counts().shape).reset_index(name='Nr')

            filename    Nr
0     batch_ar_1.csv  (4,)
1    batch_ar_10.csv  (4,)
2    batch_ar_11.csv  (4,)
3    batch_ar_12.csv  (4,)
4    batch_ar_13.csv  (4,)
..               ...   ...
110   batch_tr_5.csv  (4,)
111   batch_tr_6.csv  (4,)
112   batch_tr_7.csv  (4,)
113   batch_tr_8.csv  (4,)
114   batch_tr_9.csv  (4,)

[115 rows x 2 columns]

In [55]:
df.groupby('filename')['workerid'].apply(lambda grp: grp.unique()).reset_index()

            filename                             workerid
0     batch_ar_1.csv  [husseinsarrar, ilham, nada, gpt4o]
1    batch_ar_10.csv  [husseinsarrar, ilham, nada, gpt4o]
2    batch_ar_11.csv  [husseinsarrar, ilham, nada, gpt4o]
3    batch_ar_12.csv  [husseinsarrar, ilham, nada, gpt4o]
4    batch_ar_13.csv  [husseinsarrar, ilham, nada, gpt4o]
..               ...                                  ...
110   batch_tr_5.csv          [alp, doruk, selman, gpt4o]
111   batch_tr_6.csv          [alp, doruk, selman, gpt4o]
112   batch_tr_7.csv          [alp, doruk, selman, gpt4o]
113   batch_tr_8.csv          [alp, doruk, selman, gpt4o]
114   batch_tr_9.csv          [alp, doruk, selman, gpt4o]

[115 rows x 2 columns]

In [56]:
LANG_BATCHES = {
    'en': [f'batch_en_{i}.csv' for i in range(1,22)],
    'nl': [f'batch_nl_{i}.csv' for i in set(range(1,18)) - {3, 16}],
    'de': [f'batch_de_{i}.csv' for i in range(1,21)],
    'es': [f'batch_es_{i}.csv' for i in range(1,20)],
    'tr': [f'batch_tr_{i}.csv' for i in range(1,20)],
    'ar': [f'batch_ar_{i}.csv' for i in range(1,20)],
}

In [57]:
# define all the inter-annotator agreements we want to calculate
IAA = [
    dict(
        prefix=f'IAA_toxicity_{key}_',
        conditions=[('column_in_list', 'filename', batches)],
        to_calculate=['toxicity'],
        labels=['Yes/Maybe', 'No']
    )
    for key, batches in LANG_BATCHES.items()
] + [
    dict(
        prefix=f'IAA_counternarrative_{lang}_',
        conditions=[('column_in_list', 'filename', batches)],
        to_calculate=['counternarrative'],
        labels=COLUMNS['counternarrative'].values,
    ) for lang, batches in LANG_BATCHES.items()
] + [
    dict(
        prefix=f'IAA_justInappropriate_{lang}_',
        conditions=[
            ('column_in_list', 'filename', batches),
            ('full_agreement_on_value', 'toxicity', 'Yes/Maybe'),
            ('full_agreement_on_value', 'counternarrative', 'No'),
        ],
        to_calculate=['justInappropriate'],
        labels=COLUMNS['justInappropriate'].values,
    ) for lang, batches in LANG_BATCHES.items()
] + [
    dict(
        prefix=f'IAA_subject_{lang}_',
        conditions=[
            ('column_in_list', 'filename', batches),
            ('full_agreement_on_value', 'implDetected', True),
        ],
        to_calculate=['subject'],
        labels=COLUMNS['subject'].values,
    ) for lang, batches in LANG_BATCHES.items()
] + [
    dict(
        prefix=f'IAA_hasOther_{lang}_',
        conditions=[
            ('column_in_list', 'filename', batches),
            ('full_agreement_on_value', 'implDetected', True),
        ],
        to_calculate=['hasOther'],
        labels=COLUMNS['hasOther'].values,
    ) for lang, batches in LANG_BATCHES.items()
] + [
#     dict(
#         prefix=f'IAA_other_{lang}_',
#         conditions=[
#             ('column_in_list', 'filename', batches),
#             ('full_agreement_on_value', 'implDetected', True),
#             ('full_agreement_on_value', 'hasOther', '[]'),
#         ],
#         to_calculate=['other'],
#         labels=COLUMNS['other'].values,
#     ) for lang, batches in LANG_BATCHES.items()
# ] + [
    dict(
        prefix=f'IAA_implTopic_{lang}_',
        conditions=[
            ('column_in_list', 'filename', batches),
            ('full_agreement_on_value', 'implDetected', True),
        ],
        to_calculate=['implTopic'],
        labels=COLUMNS['implTopic'].values,
    ) for lang, batches in LANG_BATCHES.items()
] + [
    dict(
        prefix=f'IAA_implPolarity_{lang}_',
        conditions=[
            ('column_in_list', 'filename', batches),
            ('full_agreement_on_value', 'implDetected', True),
        ],
        to_calculate=['implPolarity'],
        labels=COLUMNS['implPolarity'].values,
    ) for lang, batches in LANG_BATCHES.items()
] + [
    dict(
        prefix=f'IAA_implStereotype_{lang}_',
        conditions=[
            ('column_in_list', 'filename', batches),
            ('full_agreement_on_value', 'implDetected', True),
        ],
        to_calculate=['implStereotype'],
        labels=COLUMNS['implStereotype'].values,
    ) for lang, batches in LANG_BATCHES.items()
] + [
    dict(
        prefix=f'IAA_implSarcasm_{lang}_',
        conditions=[
            ('column_in_list', 'filename', batches),
            ('full_agreement_on_value', 'implDetected', True),
        ],
        to_calculate=['implSarcasm'],
        labels=COLUMNS['implSarcasm'].values,
    ) for lang, batches in LANG_BATCHES.items()
# ] + [
#     dict(
#         prefix=f'IAA_{col}_{lang}_',
#         conditions=[
#             ('column_in_list', 'filename', batches),
#             ('full_agreement_on_value', 'implDetected', True),
#         ],
#         to_calculate=[col],
#         labels=COLUMNS[col].values,
#     )
#     for lang, batches in LANG_BATCHES.items()
#     for col in ['authorBelief', 'authorPrefer', 'authorAccount',
#                 'typicalBelief', 'typicalPrefer', 'expertBelief']
]

In [58]:
all_results = []

def iaa_calculation(suitable_df, col, key, labels, name=""):
    col = 'answer_pp_' + col
    print(key + col)
    results = []


    # calculate cohen's kappa between pairs of annotators
    # workers = suitable_df['workerid'].unique().tolist()
    # for w1, w2 in itertools.combinations(workers, r=2):
    #     w1_df = suitable_df.loc[suitable_df['workerid']==w1]
    #     w2_df = suitable_df.loc[suitable_df['workerid']==w2]
    #     valid_comment_ids = (set(w1_df.loc[w1_df[col].notna(), 'comment_id'].unique())
    #                        & set(w2_df.loc[w2_df[col].notna(), 'comment_id'].unique()))
    #     w1_df = w1_df.loc[w1_df['comment_id'].isin(valid_comment_ids)]
    #     w2_df = w2_df.loc[w2_df['comment_id'].isin(valid_comment_ids)]

    #     y1 = w1_df[col]
    #     y2 = w2_df[col]
    #     if len(y1) < len(suitable_df['comment_id'].unique()):
    #         print(f'WARNING reduced support cohen {w1} - {w2}:', len(y1), len(suitable_df['comment_id'].unique()))

    #     try:
    #         with warnings.catch_warnings():
    #             warnings.simplefilter('ignore')
    #             value = cohen_kappa_score(y1.tolist(), y2.tolist(), labels=labels)

    #         if pd.isna(value):
    #             print(f'WARNING NaN for cohen {w1} - {w2}:', y1.unique(), y2.unique())

    #         results.append({'key': key, 'col': col, 'score': 'cohen', 'w1': w1, 'w2': w2, 'support': len(y1), 'value': value})
    #     except ValueError as e:
    #         print(f'ERROR   {w1} ({len(y1)}), {w2} ({len(y2)})')
    #         ids1 = set(suitable_df.loc[y1.index]['comment_id'].unique())
    #         ids2 = set(suitable_df.loc[y2.index]['comment_id'].unique())
    #         diff1 = ids1 - ids2
    #         print(f'{w1} - {w2}:', suitable_df.loc[suitable_df['comment_id'].isin(diff1), ['filename', 'st_id']])
    #         diff2 = ids2 - ids1
    #         print(f'{w2} - {w1}:',suitable_df.loc[suitable_df['comment_id'].isin(diff2), ['filename', 'st_id']])
    #         raise e

    # calculate fleiss' kappa
    answers_by_comment = suitable_df.pivot(columns=['workerid'], index=['comment_id'], values=[col])

    def fleiss(answers_by_comment):
        valid = answers_by_comment.notna().all(axis=1)
        if valid.sum() < len(valid):
            print('WARNING reduced support fleiss:', valid.sum(), len(valid))

        table = answers_by_comment.loc[valid].to_numpy()
        table, labels = aggregate_raters(table)
        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            value = fleiss_kappa(table)
        results.append({'key': key, 'col': col, 'score': f'fleiss-{name}', 'value': value, 'support': valid.sum()})
    fleiss(answers_by_comment)

    # write answers to csv for manual checking
    # answers_by_comment.to_csv('answers_by_comment_' + name + '.csv')

    # pprint.pprint(results)
    # print('----')

    all_results.extend(results)


# calculate IAA for all annotators
conditional_calculation(df, IAA, iaa_calculation, name='all')

# calculate IAA for all annotators except gpt4o
conditional_calculation(df.drop(df.index[df['workerid'].isin(['gpt4o'])]), IAA, iaa_calculation, name='w/o gpt')



results_df = pd.DataFrame.from_dict(all_results)
results_df.to_csv('agreement_scores.csv')

IAA_toxicity_en_answer_pp_toxicity
WARNING reduced support fleiss: 499 520
IAA_toxicity_nl_answer_pp_toxicity
IAA_toxicity_de_answer_pp_toxicity
IAA_toxicity_es_answer_pp_toxicity
IAA_toxicity_tr_answer_pp_toxicity
IAA_toxicity_ar_answer_pp_toxicity
IAA_counternarrative_en_answer_pp_counternarrative
WARNING reduced support fleiss: 499 520
IAA_counternarrative_nl_answer_pp_counternarrative
IAA_counternarrative_de_answer_pp_counternarrative
IAA_counternarrative_es_answer_pp_counternarrative
IAA_counternarrative_tr_answer_pp_counternarrative
IAA_counternarrative_ar_answer_pp_counternarrative
IAA_justInappropriate_en_answer_pp_justInappropriate
IAA_justInappropriate_nl_answer_pp_justInappropriate
WARNING reduced support fleiss: 29 38
IAA_justInappropriate_de_answer_pp_justInappropriate
WARNING reduced support fleiss: 57 59
IAA_justInappropriate_es_answer_pp_justInappropriate
WARNING reduced support fleiss: 114 121
IAA_justInappropriate_tr_answer_pp_justInappropriate
WARNING reduced support fleiss: 91 103
IAA_justInappropriate_ar_answer_pp_justInappropriate
WARNING reduced support fleiss: 84 87
IAA_subject_en_answer_pp_subject
IAA_subject_nl_answer_pp_subject
IAA_subject_de_answer_pp_subject
IAA_subject_es_answer_pp_subject
IAA_subject_tr_answer_pp_subject
IAA_subject_ar_answer_pp_subject
IAA_hasOther_en_answer_pp_hasOther
IAA_hasOther_nl_answer_pp_hasOther
IAA_hasOther_de_answer_pp_hasOther
IAA_hasOther_es_answer_pp_hasOther
IAA_hasOther_tr_answer_pp_hasOther
IAA_hasOther_ar_answer_pp_hasOther
IAA_implTopic_en_answer_pp_implTopic
IAA_implTopic_nl_answer_pp_implTopic
IAA_implTopic_de_answer_pp_implTopic
IAA_implTopic_es_answer_pp_implTopic
WARNING reduced support fleiss: 44 45
IAA_implTopic_tr_answer_pp_implTopic
IAA_implTopic_ar_answer_pp_implTopic
IAA_implPolarity_en_answer_pp_implPolarity
IAA_implPolarity_nl_answer_pp_implPolarity
IAA_implPolarity_de_answer_pp_implPolarity
IAA_implPolarity_es_answer_pp_implPolarity
IAA_implPolarity_tr_answer_pp_implPolarity
IAA_implPolarity_ar_answer_pp_implPolarity
IAA_implStereotype_en_answer_pp_implStereotype
IAA_implStereotype_nl_answer_pp_implStereotype
IAA_implStereotype_de_answer_pp_implStereotype
WARNING reduced support fleiss: 17 18
IAA_implStereotype_es_answer_pp_implStereotype
IAA_implStereotype_tr_answer_pp_implStereotype
IAA_implStereotype_ar_answer_pp_implStereotype
IAA_implSarcasm_en_answer_pp_implSarcasm
IAA_implSarcasm_nl_answer_pp_implSarcasm
IAA_implSarcasm_de_answer_pp_implSarcasm
IAA_implSarcasm_es_answer_pp_implSarcasm
WARNING reduced support fleiss: 44 45
IAA_implSarcasm_tr_answer_pp_implSarcasm
WARNING reduced support fleiss: 15 16
IAA_implSarcasm_ar_answer_pp_implSarcasm
IAA_toxicity_en_answer_pp_toxicity
WARNING reduced support fleiss: 497 518
IAA_toxicity_nl_answer_pp_toxicity
IAA_toxicity_de_answer_pp_toxicity
IAA_toxicity_es_answer_pp_toxicity
WARNING reduced support fleiss: 492 493
IAA_toxicity_tr_answer_pp_toxicity
IAA_toxicity_ar_answer_pp_toxicity
IAA_counternarrative_en_answer_pp_counternarrative
WARNING reduced support fleiss: 497 518
IAA_counternarrative_nl_answer_pp_counternarrative
IAA_counternarrative_de_answer_pp_counternarrative
IAA_counternarrative_es_answer_pp_counternarrative
WARNING reduced support fleiss: 492 493
IAA_counternarrative_tr_answer_pp_counternarrative
IAA_counternarrative_ar_answer_pp_counternarrative
IAA_justInappropriate_en_answer_pp_justInappropriate
IAA_justInappropriate_nl_answer_pp_justInappropriate
WARNING reduced support fleiss: 38 49
IAA_justInappropriate_de_answer_pp_justInappropriate
WARNING reduced support fleiss: 76 78
IAA_justInappropriate_es_answer_pp_justInappropriate
WARNING reduced support fleiss: 152 162
IAA_justInappropriate_tr_answer_pp_justInappropriate
WARNING reduced support fleiss: 101 115
IAA_justInappropriate_ar_answer_pp_justInappropriate
WARNING reduced support fleiss: 87 91
IAA_subject_en_answer_pp_subject
WARNING reduced support fleiss: 46 47
IAA_subject_nl_answer_pp_subject
IAA_subject_de_answer_pp_subject
IAA_subject_es_answer_pp_subject
WARNING reduced support fleiss: 62 63
IAA_subject_tr_answer_pp_subject
WARNING reduced support fleiss: 18 19
IAA_subject_ar_answer_pp_subject
IAA_hasOther_en_answer_pp_hasOther
WARNING reduced support fleiss: 46 47
IAA_hasOther_nl_answer_pp_hasOther
IAA_hasOther_de_answer_pp_hasOther
IAA_hasOther_es_answer_pp_hasOther
WARNING reduced support fleiss: 62 63
IAA_hasOther_tr_answer_pp_hasOther
IAA_hasOther_ar_answer_pp_hasOther
IAA_implTopic_en_answer_pp_implTopic
WARNING reduced support fleiss: 46 47
IAA_implTopic_nl_answer_pp_implTopic
IAA_implTopic_de_answer_pp_implTopic
IAA_implTopic_es_answer_pp_implTopic
WARNING reduced support fleiss: 61 63
IAA_implTopic_tr_answer_pp_implTopic
IAA_implTopic_ar_answer_pp_implTopic
IAA_implPolarity_en_answer_pp_implPolarity
WARNING reduced support fleiss: 46 47
IAA_implPolarity_nl_answer_pp_implPolarity
IAA_implPolarity_de_answer_pp_implPolarity
IAA_implPolarity_es_answer_pp_implPolarity
WARNING reduced support fleiss: 62 63
IAA_implPolarity_tr_answer_pp_implPolarity
WARNING reduced support fleiss: 18 19
IAA_implPolarity_ar_answer_pp_implPolarity
IAA_implStereotype_en_answer_pp_implStereotype
WARNING reduced support fleiss: 46 47
IAA_implStereotype_nl_answer_pp_implStereotype
IAA_implStereotype_de_answer_pp_implStereotype
WARNING reduced support fleiss: 20 21
IAA_implStereotype_es_answer_pp_implStereotype
WARNING reduced support fleiss: 62 63
IAA_implStereotype_tr_answer_pp_implStereotype
IAA_implStereotype_ar_answer_pp_implStereotype
IAA_implSarcasm_en_answer_pp_implSarcasm
WARNING reduced support fleiss: 46 47
IAA_implSarcasm_nl_answer_pp_implSarcasm
IAA_implSarcasm_de_answer_pp_implSarcasm
IAA_implSarcasm_es_answer_pp_implSarcasm
WARNING reduced support fleiss: 60 63
IAA_implSarcasm_tr_answer_pp_implSarcasm
WARNING reduced support fleiss: 18 19
IAA_implSarcasm_ar_answer_pp_implSarcasm

# ...

In [59]:
from sklearn.metrics import precision_recall_fscore_support

Add majority vote

In [60]:
def scores_calculation(suitable_df, col, key, labels):
    majority = suitable_df[suitable_df['workerid']!='gpt4o'].groupby(by=['comment_id'])[f'answer_{col}'].apply(lambda x: x.mode().iloc[0]).rename('majority')
    gpt4o = suitable_df[suitable_df['workerid']=='gpt4o'].set_index('comment_id')[f'answer_{col}'].rename('gpt4o')
    both = pd.merge(majority, gpt4o, left_index=True, right_index=True, how='outer')

    both.to_csv('majority_vs_gpt4o.csv')

    y_true = both['majority'].tolist()
    y_pred = both['gpt4o'].tolist()

    result = precision_recall_fscore_support(y_true, y_pred, labels=labels)
    # result = precision_recall_fscore_support(y_true, y_pred)
    for key, val in zip(['precis', 'recall', 'fscore', 'suppor'], result):
        print(f'{key}: {val}')

    print('---------')

conditional_calculation(IAA, scores_calculation)

TypeError: conditional_calculation() missing 1 required positional argument: 'do_calc'