In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import sys
sys.path.append('/home/stefan/Projects/toxic-reasoning/')

import numpy as np
import pandas as pd

from sklearn.metrics import cohen_kappa_score
# from statsmodels.stats.inter_rater import fleiss_kappa, aggregate_raters

from data import _preprocess, COLUMNS

### LOAD TEST SET

In [4]:
# TEST_DATA_FILE_NAME = '../data/temporal/preprocessed_test.pkl'
# TEST_DATA_FILE_NAME = '../data/temporal/preprocessed+manual_test.pkl'
TEST_DATA_FILE_NAME = '../data/temporal/preprocessed+manual+corrected_test.pkl'
# test_df = _preprocess(pd.read_pickle(TEST_DATA_FILE_NAME))
test_df = pd.read_pickle(TEST_DATA_FILE_NAME)

# TODO fix this upstream somewhere
# test_df['answer_pp_toxicity'] = test_df['answer_toxicity']

# extract language from filename
test_df['lang'] = test_df['filename'].str.extract(r'batch_(..)_\d+\.csv')
test_df['lang'].unique()

array(['ar', 'de', 'en', 'es', 'nl', 'tr'], dtype=object)

In [9]:
TRAIN_DATA_FILE_NAME = '../data/temporal/preprocessed_train.pkl'
train_df = _preprocess(pd.read_pickle(TRAIN_DATA_FILE_NAME))
train_df['lang'] = train_df['filename'].str.extract(r'batch_(.*)_ChatGPT_hate_speech_or_not_\d+.csv')

Exception ignored in: <bound method IPythonKernel._clean_thread_parent_frames of <ipykernel.ipkernel.IPythonKernel object at 0x79421c10fe60>>
Traceback (most recent call last):
  File "/home/stefan/Projects/toxic-reasoning/env-models/lib/python3.12/site-packages/ipykernel/ipkernel.py", line 775, in _clean_thread_parent_frames
    def _clean_thread_parent_frames(

KeyboardInterrupt:

### Select data

In [50]:
# df = train_df
df = test_df

# Calculate statistics

In [ ]:
# we want to list the number of annotators per comment for each 'level' in the annotation hierarchy
# the columns we need to check are: 'label_toxicity', 'label_justInappropriate', 'label_implDetected'

# one batch was not annotated by illia, so use piek's annotation
temp = df[df['workerid'].isin(['stefan', 'ilia', 'baran']) | (df['lang'] != 'en') | (df['st_id'] == 7769338150590051)]

# for label_toxicity, count the number of 1s.
temp1 = temp.groupby(['lang', 'comment_id'])[['label_toxicity']].sum().reset_index()

# for label_justInappropriate, count the number of 0s.
temp2 = temp.groupby(['lang', 'comment_id'])[['label_justInappropriate']].apply(lambda x: (x == 0).sum()).reset_index()

# for answer_pp_implDetected, count the number of 1s.
temp3 = temp.groupby(['lang', 'comment_id'])[['answer_pp_implDetected']].sum().reset_index()

# now join
temp = pd.merge(temp1, temp2, on=['lang', 'comment_id'], how='outer')
temp = pd.merge(temp, temp3, on=['lang', 'comment_id'], how='outer')

# now, for each column, calculate the numbner of comments with each value, per language
toxicity_counts = temp.groupby(['label_toxicity', 'lang']).size().reset_index(name='count')
toxicity_counts = toxicity_counts.pivot(columns='lang', index='label_toxicity', values='count')
toxicity_counts['col'] = 'toxicity'

justInappr_counts = temp.groupby(['label_justInappropriate', 'lang']).size().reset_index(name='count')
justInappr_counts = justInappr_counts.pivot(columns='lang', index='label_justInappropriate', values='count')
justInappr_counts['col'] = 'justInappropriate'

implDetected_counts = temp.groupby(['answer_pp_implDetected', 'lang']).size().reset_index(name='count')
implDetected_counts = implDetected_counts.pivot(columns='lang', index='answer_pp_implDetected', values='count')
implDetected_counts['col'] = 'implDetected'

temp = pd.concat([toxicity_counts, justInappr_counts, implDetected_counts], axis=0)
temp = temp.set_index(['col'], append=True)
temp

lang                  ar   de   en   es   nl   tr
  col
0 toxicity           192  127  189  147  160  164
1 toxicity           101  119  116   85  123   69
2 toxicity           114  140  123   89   84   64
3 toxicity            99  120   92  174   52  153
0 justInappropriate  216  151  188  172  194  282
1 justInappropriate  135  153  148  109  130  104
2 justInappropriate  109  129  115  106   70   49
3 justInappropriate   46   73   69  108   25   15
0 implDetected       337  340  254  207  239  331
1 implDetected        84  100  132  146   90   61
2 implDetected        57   45   87   80   61   39
3 implDetected        28   21   47   62   29   19

## Subthread counts

In [50]:
st_counts = df.groupby('lang')[['st_id']].nunique().rename(columns={'st_id': 'Nr. sub-threads'})
st_counts

      Nr. sub-threads
lang
ar                 92
de                 97
en                102
es                 91
nl                 79
tr                 86

## Subthread lenghts

In [51]:
by_st = df.groupby(['lang', 'st_id'])[['comment_id']].nunique().reset_index()  # contains nr of comments for each sub thread
by_lang = by_st.groupby('lang')[['comment_id']]                                     # grouped by language
avg_length = by_lang.mean().rename(columns={'comment_id': 'Avg. Length'})
min_length = by_lang.min().rename(columns={'comment_id': 'Min. length'})
max_length = by_lang.max().rename(columns={'comment_id': 'Max. length'})
st_length_df = pd.concat([avg_length, min_length, max_length], axis=1)
st_length_df

      Avg. Length  Min. length  Max. length
lang
ar       5.500000            4           10
de       5.216495            4           10
en       5.098039            4           10
es       5.439560            4           10
nl       5.303797            4            9
tr       5.232558            4           10

## ...

In [52]:
# calculate counts for toxicity ('Yes/Maybe' vs. 'No'), based on majority vote
def majority_vote(series):
    modes = series.mode()
    if len(modes) == 1:
        return modes.iloc[0]
    elif len(modes) == 0:
        return None
    return "{" + ",".join(str(v) for v in modes.tolist()) + "}"

COLS = ['lang', 'comment_id', 'answer_pp_toxicity', 'answer_pp_counternarrative', 'answer_pp_justInappropriate', 'answer_pp_hasImplication', 'answer_pp_hasOther']
maj_df = df[COLS].groupby(['lang', 'comment_id']).agg(majority_vote).reset_index()

toxicity = maj_df.groupby(['lang', 'answer_pp_toxicity'])[['comment_id']].nunique().reset_index()
toxicity = toxicity.pivot(index='lang', columns='answer_pp_toxicity', values='comment_id')
toxicity['Total comments'] = toxicity['No'] + toxicity['Yes/Maybe']
toxicity = toxicity.rename(columns={'No': 'Nr. of non-toxic', 'Yes/Maybe': 'Nr. of possibly toxic comments'})
toxicity

answer_pp_toxicity,Nr. of non-toxic,Nr. of possibly toxic comments,"{No,Yes/Maybe}",Total comments
lang,,,,
ar,293.0,213.0,NaN,506.0
de,246.0,260.0,NaN,506.0
en,309.0,211.0,NaN,520.0
es,232.0,263.0,NaN,495.0
nl,265.0,136.0,18.0,401.0
tr,233.0,217.0,NaN,450.0

## Subject Group Type

In [ ]:
temp_df = df.copy() 
temp_df = temp_df.explode('answer_pp_subjectGroupType', ignore_index=True)
subjectGroupType = temp_df.groupby(['lang', 'answer_pp_subjectGroupType'])[['comment_id']].nunique().reset_index()
subjectGroupType = subjectGroupType.pivot(index='lang', columns='answer_pp_subjectGroupType', values='comment_id')
subjectGroupType

['_Political affiliation' '_Social belief' '_Religion' <NA>
 '_Race/Ethnicity' '_Nationality' '_Sexual orientation' nan
 '_Famous individual' '_Not applicable' '_other' '_Socioeconomic status'
 '_Profession' '_Gender' '_Addiction' '_Age' '_Disability' '_Body image']

answer_pp_subjectGroupType,_Addiction,_Age,_Body image,_Disability,_Famous individual,_Gender,_Nationality,_Not applicable,_Political affiliation,_Profession,_Race/Ethnicity,_Religion,_Sexual orientation,_Social belief,_Socioeconomic status,_other
lang,,,,,,,,,,,,,,,,
ar,1.0,1.0,NaN,NaN,7.0,2.0,68.0,16.0,32.0,9.0,60.0,49.0,1.0,9.0,2.0,12.0
de,NaN,12.0,NaN,NaN,2.0,23.0,51.0,35.0,23.0,20.0,19.0,13.0,3.0,35.0,5.0,34.0
en,1.0,8.0,4.0,4.0,15.0,16.0,88.0,35.0,91.0,33.0,57.0,30.0,8.0,24.0,8.0,73.0
es,4.0,8.0,6.0,2.0,11.0,30.0,81.0,77.0,42.0,59.0,36.0,16.0,5.0,58.0,51.0,34.0
nl,NaN,5.0,NaN,5.0,15.0,8.0,51.0,63.0,34.0,6.0,12.0,16.0,5.0,17.0,11.0,42.0
tr,NaN,NaN,1.0,NaN,9.0,7.0,41.0,5.0,32.0,1.0,46.0,20.0,2.0,23.0,5.0,10.0

## Has Other

In [56]:
hasOther = df.groupby(['lang', 'label_hasOther'])[['comment_id']].nunique().reset_index()
hasOther = hasOther.pivot(index='lang', columns='label_hasOther', values='comment_id')
hasOther

label_hasOther  -100   0     1
lang
ar               486   150    21
de               492    91    80
en               518   142   104
es               437   246    57
nl               397   123    59
tr               440    90    32

## Subject Role

In [57]:
subject = df.groupby(['lang', 'answer_pp_subject'])[['comment_id']].nunique().reset_index()
subject = subject.pivot(index='lang', columns='answer_pp_subject', values='comment_id')
subject

answer_pp_subject,an individual outside of the conversation,another group,another participant in the conversation and/or the group they belong to,none of the above,the author themselves and/or their ingroup
lang,,,,,
ar,11,126,41,5,23
de,15,113,45,10,16
en,28,184,41,5,7
es,39,202,57,23,19
nl,26,104,61,4,2
tr,14,96,16,13,6

## Implication Temporality

In [54]:
temp_df = df.explode('answer_pp_implTemporality', ignore_index=True)
implTemp = temp_df.groupby(['lang', 'answer_pp_implTemporality'])[['comment_id']].nunique().reset_index()
implTemp = implTemp.pivot(index='lang', columns='answer_pp_implTemporality', values='comment_id')
implTemp

answer_pp_implTemporality  _Future  _Past  _Present
lang
ar                              25     63       159
de                              47     48       164
en                              60    101       247
es                              51     38       263
nl                              34     28       171
tr                              26     49       108

In [55]:
temp_df = df.copy()
temp_df['answer_pp_implTemporality'] = temp_df['answer_pp_implTemporality'].astype(str)
implTemp= temp_df.groupby(['lang', 'answer_pp_implTemporality'])[['comment_id']].nunique().reset_index()
implTemp= implTemp.pivot(index='lang', columns='answer_pp_implTemporality', values='comment_id')
implTemp

answer_pp_implTemporality,<NA>,['_Future'],"['_Past', '_Future']","['_Past', '_Present', '_Future']","['_Past', '_Present']",['_Past'],"['_Present', '_Future']",['_Present'],[]
lang,,,,,,,,,
ar,478.0,6.0,NaN,6.0,48.0,19.0,17.0,126.0,NaN
de,485.0,4.0,NaN,22.0,27.0,3.0,22.0,119.0,NaN
en,475.0,22.0,NaN,28.0,46.0,36.0,16.0,204.0,2.0
es,433.0,32.0,1.0,1.0,16.0,23.0,22.0,244.0,4.0
nl,381.0,19.0,NaN,3.0,17.0,11.0,17.0,152.0,3.0
tr,431.0,5.0,NaN,10.0,26.0,18.0,14.0,85.0,4.0

## Implication Property

In [58]:
impl_topic = df.groupby(['lang', 'answer_pp_implTopic'])[['comment_id']].nunique().reset_index()
impl_topic = impl_topic.pivot(index='lang', columns='answer_pp_implTopic', values='comment_id')
impl_topic

answer_pp_implTopic   (a)  (a.1)    (b)  (b.1)    (c)   (d)   (e)
lang
ar                   14.0   11.0   54.0    8.0  122.0   7.0  11.0
de                   20.0   11.0   64.0    4.0   96.0   2.0   9.0
en                   44.0   30.0   67.0    3.0  201.0  11.0   6.0
es                   45.0   29.0  118.0   26.0  141.0   3.0  20.0
nl                   16.0   23.0   24.0    3.0  149.0   3.0   3.0
tr                    9.0    NaN   40.0   13.0   78.0   5.0   3.0

## Implication Polarity

In [59]:
impl_polarity = df.groupby(['lang', 'answer_pp_implPolarity'])[['comment_id']].nunique().reset_index()
impl_polarity = impl_polarity.pivot(index='lang', columns='answer_pp_implPolarity', values='comment_id')
impl_polarity

answer_pp_implPolarity  Negative  Neutral  Positive
lang
ar                         157.0     13.0      10.0
de                         160.0      6.0       8.0
en                         219.0     83.0      23.0
es                         275.0     21.0       8.0
nl                         169.0     10.0      12.0
tr                         115.0      6.0       NaN

## Implication Sarcasm

In [62]:
impl_sarcasm = df.groupby(['lang', 'answer_pp_implSarcasm'])[['comment_id']].nunique().reset_index()
impl_sarcasm = impl_sarcasm.pivot(index='lang', columns='answer_pp_implSarcasm', values='comment_id')
impl_sarcasm

answer_pp_implSarcasm   No  Yes
lang
ar                     161   10
de                     133   47
en                     202  113
es                     199  145
nl                     162   33
tr                      99   46

## Implication Stereotype

In [63]:
impl_stereo = df.groupby(['lang', 'answer_pp_implStereotype'])[['comment_id']].nunique().reset_index()
impl_stereo = impl_stereo.pivot(index='lang', columns='answer_pp_implStereotype', values='comment_id')
impl_stereo

answer_pp_implStereotype   No  Yes
lang
ar                        156   33
de                        115   70
en                        241   91
es                        192  183
nl                        160   38
tr                         84   84

# Table 1

In [60]:
MAPPING = {
    '(a)': 'Situational', '(a.1)': 'Harm',
    '(b)': 'Qualitative', '(b.1)': 'Dehumanization',
    '(c)': 'Behavioral',
    '(d)': '-NonSpecific',
    '(e)': '-UnclearOrNone',
}
ILLEGAL = ['PositiveHarm', 'NeutralHarm', 'PositiveDehumanization', 'NeutralDehumanization']

def convert(row):
    topic = row['answer_pp_implTopic']
    polarity = row['answer_pp_implPolarity']
    if pd.isna(topic):
        return pd.NA
    name = str(MAPPING[topic]) if topic.endswith('.1)') else str(polarity) + str(MAPPING[topic])
    if name in ILLEGAL:
        return 'ILLEGAL'
    return name

implType = pd.concat([df[['lang', 'comment_id']], df.apply(convert, axis=1).rename('Implication Type')], axis=1)
implType = implType.groupby(['lang', 'Implication Type'])['comment_id'].nunique().reset_index()
implType = implType.pivot(index='lang', columns='Implication Type', values='comment_id')
implType

Implication Type,Dehumanization,Harm,Negative-NonSpecific,Negative-UnclearOrNone,NegativeBehavioral,NegativeQualitative,NegativeSituational,Neutral-NonSpecific,Neutral-UnclearOrNone,NeutralBehavioral,...,NeutralSituational,None-UnclearOrNone,NoneBehavioral,NoneQualitative,NoneSituational,Positive-NonSpecific,Positive-UnclearOrNone,PositiveBehavioral,PositiveQualitative,PositiveSituational
lang,,,,,,,,,,,,,,,,,,,,,
ar,8.0,11.0,2.0,8.0,116.0,51.0,12.0,1.0,3.0,6.0,...,1.0,NaN,NaN,NaN,NaN,4.0,NaN,4.0,2.0,1.0
de,4.0,11.0,2.0,5.0,90.0,62.0,17.0,NaN,NaN,2.0,...,2.0,3.0,NaN,NaN,NaN,NaN,1.0,5.0,NaN,2.0
en,3.0,30.0,3.0,2.0,167.0,46.0,30.0,7.0,3.0,43.0,...,9.0,1.0,3.0,NaN,NaN,1.0,NaN,12.0,4.0,5.0
es,26.0,29.0,2.0,12.0,135.0,110.0,41.0,NaN,8.0,5.0,...,3.0,NaN,NaN,2.0,1.0,1.0,NaN,5.0,2.0,1.0
nl,3.0,23.0,NaN,2.0,139.0,24.0,11.0,3.0,1.0,5.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,7.0,NaN,5.0
tr,13.0,NaN,5.0,3.0,76.0,37.0,9.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
print([type(x) for x in [st_counts, st_length_df, toxicity, impl_topic, impl_polarity, implType]])

all_stats = pd.concat([st_counts, st_length_df, toxicity, impl_topic, impl_polarity, implType], axis=1)
all_stats = all_stats.transpose()
all_stats.to_csv('data_stats.csv')
all_stats

[<class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.frame.DataFrame'>]

lang,ar,de,en,es,nl,tr
Nr. sub-threads,92.0,97.000000,102.000000,91.00000,79.000000,86.000000
Avg. Length,5.5,5.216495,5.098039,5.43956,5.303797,5.232558
Min. length,4.0,4.000000,4.000000,4.00000,4.000000,4.000000
Max. length,10.0,10.000000,10.000000,10.00000,9.000000,10.000000
Nr. of non-toxic,293.0,246.000000,309.000000,232.00000,265.000000,233.000000
Nr. of possibly toxic comments,213.0,260.000000,211.000000,263.00000,136.000000,217.000000
"{No,Yes/Maybe}",NaN,NaN,NaN,NaN,18.000000,NaN
Total comments,506.0,506.000000,520.000000,495.00000,401.000000,450.000000
(a),14.0,20.000000,44.000000,45.00000,16.000000,9.000000
(a.1),11.0,11.000000,30.000000,29.00000,23.000000,NaN
(b),54.0,64.000000,67.000000,118.00000,24.000000,40.000000
(b.1),8.0,4.000000,3.000000,26.00000,3.000000,13.000000
(c),122.0,96.000000,201.000000,141.00000,149.000000,78.000000
(d),7.0,2.000000,11.000000,3.00000,3.000000,5.000000
(e),11.0,9.000000,6.000000,20.00000,3.000000,3.000000
Negative,157.0,160.000000,219.000000,275.00000,169.000000,115.000000
Neutral,13.0,6.000000,83.000000,21.00000,10.000000,6.000000
Positive,10.0,8.000000,23.000000,8.00000,12.000000,NaN
Dehumanization,8.0,4.000000,3.000000,26.00000,3.000000,13.000000
Harm,11.0,11.000000,30.000000,29.00000,23.000000,NaN
Negative-NonSpecific,2.0,2.000000,3.000000,2.00000,NaN,5.000000
Negative-UnclearOrNone,8.0,5.000000,2.000000,12.00000,2.000000,3.000000
NegativeBehavioral,116.0,90.000000,167.000000,135.00000,139.000000,76.000000
NegativeQualitative,51.0,62.000000,46.000000,110.00000,24.000000,37.000000
NegativeSituational,12.0,17.000000,30.000000,41.00000,11.000000,9.000000
Neutral-NonSpecific,1.0,NaN,7.000000,NaN,3.000000,NaN
Neutral-UnclearOrNone,3.0,NaN,3.000000,8.00000,1.000000,NaN
NeutralBehavioral,6.0,2.000000,43.000000,5.00000,5.000000,2.000000
NeutralQualitative,1.0,2.000000,20.000000,5.00000,NaN,4.000000
NeutralSituational,1.0,2.000000,9.000000,3.00000,NaN,NaN
None-UnclearOrNone,NaN,3.000000,1.000000,NaN,NaN,NaN
NoneBehavioral,NaN,NaN,3.000000,NaN,2.000000,NaN
NoneQualitative,NaN,NaN,NaN,2.00000,NaN,NaN
NoneSituational,NaN,NaN,NaN,1.00000,NaN,NaN
Positive-NonSpecific,4.0,NaN,1.000000,1.00000,NaN,NaN
Positive-UnclearOrNone,NaN,1.000000,NaN,NaN,NaN,NaN
PositiveBehavioral,4.0,5.000000,12.000000,5.00000,7.000000,NaN
PositiveQualitative,2.0,NaN,4.000000,2.00000,NaN,NaN
PositiveSituational,1.0,2.000000,5.000000,1.00000,5.000000,NaN