In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import json
import itertools
import os
import warnings

import numpy as np
import pandas as pd

from sklearn.metrics import cohen_kappa_score
# from statsmodels.stats.inter_rater import fleiss_kappa, aggregate_raters

from data import _preprocess, COLUMNS

/home/stefan/Projects/toxic-reasoning/env-unsloth2/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
/home/stefan/Projects/toxic-reasoning/env-unsloth2/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### LOAD TEST SET

In [3]:
TEST_DATA_FILE_NAME = '../data/temporal/preprocessed_test.pkl'
test_df = _preprocess(pd.read_pickle(TEST_DATA_FILE_NAME))

# TODO fix this upstream somewhere
test_df['answer_pp_toxicity'] = test_df['answer_toxicity']

# extract language from filename
test_df['lang'] = test_df['filename'].str.extract(r'batch_(..)_\d+\.csv')
test_df['lang'].unique()

array(['nl', 'en', 'es', 'tr', 'ar', 'de'], dtype=object)

In [4]:
TRAIN_DATA_FILE_NAME = '../data/temporal/preprocessed_train.pkl'
train_df = _preprocess(pd.read_pickle(TRAIN_DATA_FILE_NAME))
train_df['lang'] = train_df['filename'].str.extract(r'batch_(.*)_ChatGPT_hate_speech_or_not_\d+.csv')

### Select data

In [5]:
df = train_df

### Calculate statistics

In [6]:
st_counts = df.groupby('lang')[['st_id']].nunique().rename(columns={'st_id': 'Nr. sub-threads'})
st_counts

         Nr. sub-threads
lang
Arabic               296
Dutch                612
English            17833
German              1421
Spanish             3340
Turkish              940

In [7]:
by_st = df.groupby(['lang', 'st_id'])[['comment_id']].nunique().reset_index()  # contains nr of comments for each sub thread
by_lang = by_st.groupby('lang')[['comment_id']]                                     # grouped by language
avg_length = by_lang.mean().rename(columns={'comment_id': 'Avg. Length'})
min_length = by_lang.min().rename(columns={'comment_id': 'Min. length'})
max_length = by_lang.max().rename(columns={'comment_id': 'Max. length'})
st_length_df = pd.concat([avg_length, min_length, max_length], axis=1)
st_length_df

         Avg. Length  Min. length  Max. length
lang
Arabic      5.510135            4           10
Dutch       5.388889            4           10
English     5.199181            4           10
German      5.160450            4           10
Spanish     5.206886            4           10
Turkish     5.427660            4           10

In [8]:
# calculate counts for toxicity ('Yes/Maybe' vs. 'No'), based on majority vote
def majority_vote(series):
    modes = series.mode()
    if len(modes) == 1:
        return modes.iloc[0]
    elif len(modes) == 0:
        return None
    return "{" + ",".join(str(v) for v in modes.tolist()) + "}"

COLS = ['lang', 'comment_id', 'answer_pp_toxicity', 'answer_pp_counternarrative', 'answer_pp_justInappropriate', 'answer_pp_hasImplication', 'answer_pp_hasOther']
maj_df = df[COLS].groupby(['lang', 'comment_id']).agg(majority_vote).reset_index()

toxicity = maj_df.groupby(['lang', 'answer_pp_toxicity'])[['comment_id']].nunique().reset_index()
toxicity = toxicity.pivot(index='lang', columns='answer_pp_toxicity', values='comment_id')
toxicity['Total comments'] = toxicity['No'] + toxicity['Yes/Maybe']
toxicity = toxicity.rename(columns={'No': 'Nr. of non-toxic', 'Yes/Maybe': 'Nr. of possibly toxic comments'})
toxicity

answer_pp_toxicity,Nr. of non-toxic,Nr. of possibly toxic comments,Total comments
lang,,,
Arabic,1034,597,1631
Dutch,2249,1049,3298
English,62224,30493,92717
German,5389,1944,7333
Spanish,10533,6858,17391
Turkish,3097,2005,5102

In [9]:
impl_topic = df.groupby(['lang', 'answer_pp_implTopic'])[['comment_id']].nunique().reset_index()
impl_topic = impl_topic.pivot(index='lang', columns='answer_pp_implTopic', values='comment_id')
impl_topic

answer_pp_implTopic     (a)   (a.1)     (b)  (b.1)      (c)     (d)   (e)
lang
Arabic                 33.0    28.0   223.0   23.0    240.0    19.0   NaN
Dutch                  51.0    97.0   369.0   25.0    423.0    39.0   3.0
English              1950.0  2957.0  8705.0  763.0  13436.0  1623.0  17.0
German                149.0   176.0   583.0   83.0    799.0    80.0   1.0
Spanish               477.0   571.0  2496.0  333.0   2412.0   230.0   3.0
Turkish                81.0   148.0   603.0  148.0    574.0    36.0   1.0

In [10]:
impl_polarity = df.groupby(['lang', 'answer_pp_implPolarity'])[['comment_id']].nunique().reset_index()
impl_polarity = impl_polarity.pivot(index='lang', columns='answer_pp_implPolarity', values='comment_id')
impl_polarity

answer_pp_implPolarity  Negative  Neutral  Positive
lang
Arabic                       555        2         9
Dutch                        993       12         2
English                    29160      189       102
German                      1849       16         6
Spanish                     6451       51        20
Turkish                     1578       10         3

In [11]:
MAPPING = {
    '(a)': 'Circumstances', '(a.1)': 'Harm',
    '(b)': 'Qualities', '(b.1)': 'Dehumanization',
    '(c)': 'Choices',
    '(d)': '-NonSpecific',
    '(e)': '-UnclearOrNone',
}
ILLEGAL = ['PositiveHarm', 'NeutralHarm', 'PositiveDehumanization', 'NeutralDehumanization']

def convert(row):
    topic = row['answer_pp_implTopic']
    polarity = row['answer_pp_implPolarity']
    if pd.isna(topic):
        return pd.NA
    name = str(MAPPING[topic]) if topic.endswith('.1)') else str(polarity) + str(MAPPING[topic])
    if name in ILLEGAL:
        return 'ILLEGAL'
    return name

implType = pd.concat([df[['lang', 'comment_id']], df.apply(convert, axis=1).rename('Implication Type')], axis=1)
implType = implType.groupby(['lang', 'Implication Type'])['comment_id'].nunique().reset_index()
implType = implType.pivot(index='lang', columns='Implication Type', values='comment_id')
implType

Implication Type,Dehumanization,Harm,Negative-NonSpecific,Negative-UnclearOrNone,NegativeChoices,NegativeCircumstances,NegativeQualities,Neutral-NonSpecific,Neutral-UnclearOrNone,NeutralChoices,NeutralCircumstances,NeutralQualities,Positive-NonSpecific,PositiveChoices,PositiveCircumstances,PositiveQualities
lang,,,,,,,,,,,,,,,,
Arabic,23.0,28.0,18.0,NaN,231.0,32.0,223.0,NaN,NaN,2.0,NaN,NaN,1.0,7.0,1.0,NaN
Dutch,25.0,97.0,36.0,2.0,415.0,51.0,367.0,2.0,1.0,7.0,NaN,2.0,1.0,1.0,NaN,NaN
English,763.0,2957.0,1549.0,13.0,13296.0,1930.0,8667.0,55.0,4.0,87.0,13.0,26.0,19.0,53.0,7.0,12.0
German,83.0,176.0,78.0,1.0,785.0,145.0,582.0,2.0,NaN,8.0,4.0,1.0,NaN,6.0,NaN,NaN
Spanish,333.0,571.0,216.0,3.0,2376.0,471.0,2481.0,11.0,NaN,22.0,5.0,13.0,3.0,14.0,1.0,2.0
Turkish,148.0,148.0,31.0,NaN,573.0,77.0,601.0,2.0,1.0,1.0,4.0,2.0,3.0,NaN,NaN,NaN

In [12]:
print([type(x) for x in [st_counts, st_length_df, toxicity, impl_topic, impl_polarity, implType]])

all_stats = pd.concat([st_counts, st_length_df, toxicity, impl_topic, impl_polarity, implType], axis=1)
all_stats = all_stats.transpose()
all_stats.to_csv('data_stats.csv')
all_stats

[<class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.frame.DataFrame'>, <class 'pandas.core.frame.DataFrame'>]

lang,Arabic,Dutch,English,German,Spanish,Turkish
Nr. sub-threads,296.000000,612.000000,17833.000000,1421.00000,3340.000000,940.00000
Avg. Length,5.510135,5.388889,5.199181,5.16045,5.206886,5.42766
Min. length,4.000000,4.000000,4.000000,4.00000,4.000000,4.00000
Max. length,10.000000,10.000000,10.000000,10.00000,10.000000,10.00000
Nr. of non-toxic,1034.000000,2249.000000,62224.000000,5389.00000,10533.000000,3097.00000
Nr. of possibly toxic comments,597.000000,1049.000000,30493.000000,1944.00000,6858.000000,2005.00000
Total comments,1631.000000,3298.000000,92717.000000,7333.00000,17391.000000,5102.00000
(a),33.000000,51.000000,1950.000000,149.00000,477.000000,81.00000
(a.1),28.000000,97.000000,2957.000000,176.00000,571.000000,148.00000
(b),223.000000,369.000000,8705.000000,583.00000,2496.000000,603.00000
(b.1),23.000000,25.000000,763.000000,83.00000,333.000000,148.00000
(c),240.000000,423.000000,13436.000000,799.00000,2412.000000,574.00000
(d),19.000000,39.000000,1623.000000,80.00000,230.000000,36.00000
(e),NaN,3.000000,17.000000,1.00000,3.000000,1.00000
Negative,555.000000,993.000000,29160.000000,1849.00000,6451.000000,1578.00000
Neutral,2.000000,12.000000,189.000000,16.00000,51.000000,10.00000
Positive,9.000000,2.000000,102.000000,6.00000,20.000000,3.00000
Dehumanization,23.000000,25.000000,763.000000,83.00000,333.000000,148.00000
Harm,28.000000,97.000000,2957.000000,176.00000,571.000000,148.00000
Negative-NonSpecific,18.000000,36.000000,1549.000000,78.00000,216.000000,31.00000
Negative-UnclearOrNone,NaN,2.000000,13.000000,1.00000,3.000000,NaN
NegativeChoices,231.000000,415.000000,13296.000000,785.00000,2376.000000,573.00000
NegativeCircumstances,32.000000,51.000000,1930.000000,145.00000,471.000000,77.00000
NegativeQualities,223.000000,367.000000,8667.000000,582.00000,2481.000000,601.00000
Neutral-NonSpecific,NaN,2.000000,55.000000,2.00000,11.000000,2.00000
Neutral-UnclearOrNone,NaN,1.000000,4.000000,NaN,NaN,1.00000
NeutralChoices,2.000000,7.000000,87.000000,8.00000,22.000000,1.00000
NeutralCircumstances,NaN,NaN,13.000000,4.00000,5.000000,4.00000
NeutralQualities,NaN,2.000000,26.000000,1.00000,13.000000,2.00000
Positive-NonSpecific,1.000000,1.000000,19.000000,NaN,3.000000,3.00000
PositiveChoices,7.000000,1.000000,53.000000,6.00000,14.000000,NaN
PositiveCircumstances,1.000000,NaN,7.000000,NaN,1.000000,NaN
PositiveQualities,NaN,NaN,12.000000,NaN,2.000000,NaN